### ISSUE TITLE
Read/write disk speed functions

### ISSUE THREAD

**Issue by basilroztor95** [ashish-yadav11/dsblocks#1]
It would be cool if there was a disk_io function from /sys/class/block/*/stat. In the form of disk read/write speed. Read is the third and write is the seventh columns.

**Comment by ashish-yadav11** [comment]
Providing blocks is not the aim of the project. The aim is to provide a framework on which users can add their own blocks.

That said, one thing you can do is write a shell script to extract the read/write speed using say awk and then get the output by using `getcmdout` function defined in `util.c`.

If you want the block in C, you can use `opendir` on `/sys/class/block` and then `readdir` in a while loop. This will give you all the directories in `/sys/class/block` (don't forget to eliminate `.` and `..`). You can `opendir` those directories and `readdir` in another loop checking the type and name until it matches `stat`. That way you will get to the required files. Then you can read the files and get the required info from each file adding it to a variable as the loop progress. I hope you get the idea.

**Comment by ashish-yadav11** [comment]
I am going to add a contrib folder in the project where users can contribute their own blocks. So if you do write this one, do consider adding a pull request.

**Comment by basilroztor95** [comment]
Thanks for the explanation!
